### ISSUE TITLE
[RFC] EPT - Revised Interface and Implementation

### ISSUE THREAD

**Issue by JaredWright** [Bareflank/extended_apis#32]
This RFC proposes a new implementation for interacting with the Extended Page Tables (EPT) on Intel systems using the Bareflank Extended APIs. The implementation that exists now is mostly working but has a few drawbacks, most notably:

* **Inefficient memory usage**: For each page table and page table entry in the EAPIs, the vmm allocates both a C++ object (internal state and member functions), plus additionally memory for the actual page table/page table entry to be used by hardware.
* **Interface redundancies**: Functions for mapping and unmapping pages exist as member functions on both the existing "root_ept" and "ept" classes.

## Proposed New Interface

I'd like to propose getting rid of the existing ept and ept_entry classes, and shrinking the existing root_ept class into a smaller *memory_map* class. This would represent the entire memory map for the extended page tables, and would provide facilities to operate directly on the page tables/entries used by hardware (instead of C++ objects). This single class will aim to define the smallest public interface possible to add a page, remove a page, and resolve mappings within the memory map. More specific functions (adding multiple pages, pages with attributes, etc) will be implemented as helper functions on top of the basic interface. Helper functions will be defined in the same namespace as the memory_map class, but not as member functions.  See the C++ core guidelines  [section C.4](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#c4-make-a-function-a-member-only-if-it-needs-direct-access-to-the-representation-of-a-class) and [section C.5](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#c5-place-helper-functions-in-the-same-namespace-as-the-class-they-support) for my thoughts behind that design choice.

### Class memory_map

The memory_map class will be defined along the lines of the following (theres probably some errors, but it conveys the idea):

```
namespace eapis
{
namespace intel_x64
{
namespace ept
{
class EXPORT_EAPIS_HVE memory_map
{
public:
    // Constructors and destructor omitted...

    // Create a mapping from guest physical -> host physical using a page of granularity g
    // Returns the last (most granular) page table entry in the mapping (the real entry, not an object)
    ept_entry_type & map(integer_pointer gpa, integer_pointer hpa, granularity_type g);
 
    // Remove the memory mapping for the given extended page table entry
    void unmap(ept_entry_type & entry) noexcept;
  
    // Guest physical address to leaf extended page table entry
    integer_pointer gpa_to_epte(integer_pointer gpa) noexcept;

    // Guest physical address to host physical address
     integer_pointer gpa_to_hpa(integer_pointer gpa) noexcept;

    // Host physical address to guest physical address (first occurrence)
    integer_pointer hpa_to_gpa(integer_pointer gpa) noexcept;

    // Convert this memory map to a flat memory descriptor list
    memory_descriptor_list to_mdl() const;

    // Return eptp (base physical address of this memory map)
    pointer eptp() noexcept;

private:
    uintptr_t m_eptp;
    mutable std::mutex m_mutex;
}
```

Also, the only data that a memory_map object stores will be the base address of the root page table (i.e. what eptp will point to) and a mutex to synchronize access. Therefore, the implementation will walk/allocate the real page tables each time it adds a new mapping, and will use the memory_manager to resolve virtual addresses of physical addresses to the extended page tables to ```delete``` them.

### EPT Helper Functions

Helper functions will be provided as the "easy to use" versions of the memory_map's interface. A lot of these helper functions already exist, they will just be "moved off" of the existing ept and ept_entry objects. Here are some examples:
 
```
namespace eapis
{
namespace intel_x64
{
namespace ept
{

// Map a GB page with attributes
void
map_1g(memory_map &map, integer_pointer gpa, integer_pointer hpa, attr_type attr);

// Map a 2MB page with attributes
void
map_2m(memory_map &map, integer_pointer gpa, integer_pointer hpa, attr_type attr);

// Map a 4KB page with attributes
void
map_4k(memory_map &map, integer_pointer gpa, integer_pointer hpa, attr_type attr);

// Identity map helpers (1 GB page or many GB pages)
void identity_map_1g(memory_map &map, integer_pointer gpa);
void identity_map_1g(memory_map &map, integer_pointer gpa, size_type count);

// Other identity mapping helpers for 2MB and 4MB pages will go here...

// Unmapping will operate on page table entries
void unmap(memory_map &map, ept_entry_type &entry) noexcept;

// Other helpers will be implemented to do things like set fields in page table entries, settings addresses in page table entries, etc.

```

The key thing here is that all of the helper functions will operate directly on the page tables/page table entries (not c++ objects) using the interface provided by the memory_map class. The memory_map's internal implementation details will handle all of the complexities of walking the page tables to locate entries and resolve addresses.

**Comment by Randshot** [comment]
If we decide to do this, I would like to request an atomic way to modify page table entries.
The helpers are nice and all, but when you want to modify an entry in one atomic operation, they don't really help. This is one point which bugged me with the current EPT implementation, since that one didn't give direct access to the EPTE pointer, which is why I added a getter method for myself (which accidentally sneaked it's way into the port PR).

**Comment by JaredWright** [comment]
I love it. That should definitely be possible if we go in this direction, because the memory map would be returning real epte references. By atomic, do you mean have the ability to modify an epte such that it is guaranteed to become visible to all observers of the memory map *immediately* after the entry is modified? Should be possible...

**Comment by Randshot** [comment]
By atomic I just meant that there shouldn't occur any race condition when modifying the entries.

**Comment by rianquinn** [comment]
Just a side not... all RFC should be placed in the main "hypervisor" repo so that the entire watch list has an opportunity to comment. 

Here are my comments:
- I'm not a fan of trying get the EPT logic to be "ARM" compatible. Although I'm sure there are some places where the interfaces (and even logic) might be the same, its confusing (as they are not named the same thing), and it overcomplicates things. Implement EPT as just Intel for now, and then when it comes time to do ARM, implement the ARM side by itself, and then when we are done, and we can see what things are common, we can address "generalization" later. It's the same rule of thumb as optimization. Don't attempt to generalize / optimize while designing as it will almost certainly change when you have a better idea of what the code looks like. 
- The code would read: `ept::ept_memory_map`, so I would just drop the `ept_` since that is redundant. 
- map should have 1g, 2m and 4k versions instead of a granularity field. This was a design choice that was intentional, and already debated as it reads easier, and is actually less verbose. Same for unmap. 
- `resolve_address` seems pretty non-standard. In Linux, that would be virt_to_phys. For ept, this should read "gpa_to_hpa" for guest physical address to host physical address. 
- resolve_mapping? What is the reason for this?
- get_base_address should be renamed to "eptp". EPT is an Intel only thing, so lets use Intel's naming scheme. Also.... we stick to the standard C++ conventions which don't have "get_" functions. 
- Your missing some functions that are critical. Like ept_to_mdl (which should probably just be called mdl). This is needed because we need to know what the list physical address is of each page table for mapping on the hyperkernel side of things. You are also missing gpa_to_epte, which converts a guest physical address to it's corresponding EPT entry. This is also a critical function as this is how extensions will modify the bits in an entry. Now, I know you plan to have helpers for this, but helpers rely on a public interface first. 
- I see that you are storing the eptp as a unique_ptr, and I assume that you are going to new/delete memory for the page tables themselves which will trigger errors with Clang Tidy as new/delete and even worse malloc/free are not allowed. What is the plan here?
- I would like to see what plans we have for lookup caching. I don't want something like this to be implemented now, but it will be needed in the future. For example, when you map memory from one guest to another, you have to walk the EPT for one guest to get it's hpa given a gpa, and then map that hpa into the other guest's EPTs. When this is done, usually more than one EPTE will be mapped, and this walk is very expensive. Other hypervisors cache the walk to help with this, but you have to be careful because you don't want to introduce race conditions with more than on CPU attempting to do a lookup / map. 

Also, we really need a lot of input from Dr. Tom on this one as he wrote a lot of the EPT logic for Xen.

**Comment by rianquinn** [comment]
Oh... and what do you mean by: `class EXPORT_EAPIS_HVE ept_memory_map(memory_manager::memory_map)` as the syntax is wrong here so I'm struggling to figure out what the memory manager has to do with this.

**Comment by rianquinn** [comment]
Also, we should probably address the MTRR issue with this PR as well. For more information, please see the following:
https://github.com/ionescu007/SimpleVisor/commit/9891d1048fc6e08b3d2b5929c6def43f7112698f

**Comment by JaredWright** [comment]
Responses for @rianquinn 

1. I definitely intend to work on intel-specific features only. I included the "ARM compatible" statement as an observation that the memory map *interface* will likely end up being the same (I agree that the implementations for that interface and the helper functions will be completely different). For now I'll focus on intel only (even though my next task is to implement this for ARM ;))

2. Agreed, I will drop the ept_ prefix from ept::ept_memory_map so it becomes ept::memory_map

3. The granularity functions (map_1g, map_2m, identity_map_1g) are still there, I proposed to move them off of the memory map class and instead implementing them as helper functions in the ept:: namespace, following C++ core guideline [C.4](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#c4-make-a-function-a-member-only-if-it-needs-direct-access-to-the-representation-of-a-class). If we did it that way, there would only be one mapping function we would need to test extensively (the ```map``` member function of ept::memory_map).

4. I named it ```resolve_address``` with the thought that this is a member function of a memory map object, and the service that object is providing to you is resolving an address. However I'd be fine naming it ```gpa_to_hpa``` or ```virt_to_phys``` to follow other existing naming schemes.

5. ``` resolve_mapping``` is a terrible name (thoughts a better one?), but this would be the function that translates a guest-physical address to a list of all extended page table entries used in its mapping (i.e. all entries used to resolve the mapping of gpa->hpa, which will likely consist of more than one epte). I was thinking that helper functions would be implemented on top of this to cover things like converting gpa->epte (which is really asking "what is the most granular epte used in the mapping for gpa->hpa").

6. Agreed, maybe we should follow guideline [C.131](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#c131-avoid-trivial-getters-and-setters) to its full potential and get rid of the accessor function altogether, making eptp a public member?

7. Agreed that I left the mdl functions out (accident). I'll revise the memory_map class to have one member function for converting to mdl. How about naming the function ```to_mdl```, because mdl sounds like a data member? As for the "gpa_to_epte like" functions, see comment 5.

8. I don't know the most C++ compatible way to go about this yet. But yes, the memory_map implementation would need to allocate and manage memory for the page tables it constructs somehow... I'll have to look into this once I start implementation. Is there an obvious way to do this? Something like ```std::make_unique<epte_t[]>(number_of_entries)```?

9. I'll cross the lookup-caching bridge when we get there. :)

10. ```class EXPORT_EAPIS_HVE ept_memory_map(memory_manager::memory_map)``` is a copy-paste error from my scratch pad design file, which is written mostly in english... haha.

11. I'll have to look into the MTRR issue more

I'll try to update the first comment of the RFC to reflect this discussion shortly...

**Comment by rianquinn** [comment]
3: Agreed
4: gpa_to_hpa is better
5: I don't think this is needed. For now I would remove this. 
6: Currently the root class has a eptp function which returns the eptp that is needed for the EPT instance you have created. This is a lot better. 
7: to_mdl is fine, and is consistent. I really want "gpa_to_epte". You almost never care about the entries that lead up to your "leaf" entry, and the use of std:vector is really bad because it causes a malloc / free which will result in a performance hit and fragmentation. This function will be used a lot, so it needs to be as fast as possible. This is where caching will also have to be implemented in the future. 
8: See below
9: Agreed, just don't forget about it
10: Np

So there are two different things that have to be managed with page tables... the page table, and the virtual address to the page table. Before we implement anything, we should lookup what the best data structure is for this, that is both performant, and doesn't waste space or cause fragmentation on large numbers of operations. Since we are going to be using a buddy allocator, the data structure really should only ever allocate pages for its backing memory. I would like to see how this is designed as part of this RFC as it's critical to the operation of the entire hypervisor (as this code will be used a lot). This would also be a good place to address atomic operations as pointed out by @Randshot.

Also, get rid of the return value for the "map_1g" functions. These should just return void as you should not be returning std::vector (one again this performs a malloc so it should be avoided).

**Comment by JaredWright** [comment]
5. I have a feeling this will be needed at some point, although I agree that the use of std::vector would not be the fastest way to return the results. Scenario: someone maps a few 4kb pages with different attributes that are all within the same 2mb region, and then later wants to unmap all of the 4kb pages simultaneously by un-mapping at the 2mb granularity. If we only provide a single gpa_to_epte function, the use of the interface is limited to manipulating leaf pages within the memory map (there is no way to access non-leaf pages). Is thats fine for the time being? If so, I'll follow your suggestion for a ```gpa_to_epte``` member function that just retrieves a leaf page. If that is not acceptable, a ```gpa_to_epte_list``` member function of memory_map could return a list of epte's in a superior structure than std::vector, and the ```gpa_to_epte``` function could be implemented as a helper function on top of that.

6. I'm totally fine with making an eptp member function to retrieve a private eptp member, but "this is a lot better" is not what the C++ core guidelines says about doing that ;)

7. (same comments as number 5)

8. Maybe I'm not quite understanding what you mean by managing the "virtual address to the page tables". Aren't the addresses to every page table in the memory map already contained *within* the page tables entries themselves? I think the only thing you need to store in the memory map object is EPTP (which points to PML4, the first table in the map). The address of every other page table in the map is calculable using the extended page table entries that make up each table. Are you suggesting that we need a separate data structure to hold the addresses of each page table in the map?

**Comment by rianquinn** [comment]
5: I don't want to over complicate the interface at the moment. For now, this is not needed for what has to be done, and users can always add this functionality themselves if they really need it. We can always revisit this if we get a ton of requests for this type of functionality. Just make sure the map / unmap functions are symmetrical, and we should be fine. 

6: eptp would not be accessing a private memory. The eptp value is a combination of the physical address, + access right and caching properties. It's an actual public function that performs work. 

7: Same thing, I want to keep the interface simple. We can always add additional functionality in the future as it is requested. 

8: No. The physical address is, but not the virtual address which is what you have to maintain, otherwise you have no idea what to pass to delete[].

**Comment by Randshot** [comment]
@rianquinn 
_Regarding 5:_
So you are suggesting that the `eptp()` function should return the actual value of the eptp and not a pointer to it?
At the moment, there are separate function for getting the value and the pointer.

**Comment by rianquinn** [comment]
Yeah, we only need one. The user of this interface doesn't care what the virtual, or even physical address is of the EPTP, but instead just wants to store the EPTP in the VMCS when needed.

**Comment by rianquinn** [comment]
@JaredWright One option that might work well (but has disadvantages on unmapping), is to use "new" to create the page, get it's physical address (via virt_to_phys), and then on unmap, use phys_to_virt to get the virtual address back and then use "delete". There are a couple of notes on this approach:

- Pro: Dramatically less memory. This would reduce the memory needs down to just the pages used by the page tables. i.e, you would use the host's CR3 as the storage for your virtual addresses
- Con: Use of "new" / "delete". There would be no way to implement this using std::unique_ptr. We would have to find a way to get Clang Tidy to be ok with that for just this part of the code. One way to do this would be to add a header to the SDK for unsafe memory operations, and then include the GCC system header guard which will silence Clang Tidy
- Pro: Simple implementation. Since std::unique_ptr is not used, the implementation should be simple
- Con: Longer lookup times. This includes gpa_to_epte and unmap as these two functions would require a lookup, resulting in a page table walk on CR3 via phys_to_virt. In some cases, this might actually require multiple page walks as you might have to do a walk of EPT to go from gpa_to_hpa, and then phys_to_virt (which we might want to call hpa_to_hva for consistency, and to keep things explicity moving forward). 

In general, I like this approach and think that the Cons are not that big of a deal. 
- So long as we have extensive unit tests, we should be able to prove that we don't have memory leaks or corruption with respect to the use of new/delete
- Lookups don't happen as much as mapping, and mapping in this case is fast. The exception to this is VMI, as mapping / unmapping happens a lot, but in this case, we can implement an internal TLB that will get rid of the need for a page walk, and speed up the process. 

Thoughts?

@tklengyel

**Comment by tklengyel** [comment]
> The exception to this is VMI, as mapping / unmapping happens a lot, but in this case, we can implement an internal TLB that will get rid of the need for a page walk, and speed up the process.

LibVMI already has something like that implemented, both a v2p translation cache that's more akin to an actual TLB and a mapped pages cache that keeps track of least recently used pages. See https://github.com/libvmi/libvmi/blob/master/libvmi/driver/memory_cache.c. So I don't think the hypervisor needs to worry about mapping/unmapping optimization (and its related translation cost) because the application side can do that on its own.

**Comment by rianquinn** [comment]
Awesome, in that case I would say that my above implementation is likely the best way to do this as the implementation should be dirt simple. As part of this, I think it would also make sense to define our translation names:

PT:
- hva_to_pte: host virtual address to page table entry
- hva_to_hpa: host virtual address to host physical address
- hpa_to_hva: host physical address to host virtual address (first occurrence)

EPT:
- gpa_to_epte: guest physical address to extended page table entry
- gpa_to_hpa: guest physical address to host physical address
- hpa_to_gpa: host physical address to guest physical address (first occurrence)

And we should provide uintptr and void* versions of each of these functions so that we have a simple API that can be used as needed (and we should not need to add int and ptr to the names as we can use simple overloading instead as Hippomocks as a work around for that now). 

@tklengyel Are we missing any. @JaredWright is only doing the EPT part right now, but as part of my buddy allocator work for the memory manager, I will provide the CR3 side of things.

**Comment by JaredWright** [comment]
Thanks again to everyone for all of the awesome feedback on this RFC. I did my best to integrate everyone's comments into the "design" by editing the first comment of this RFC.

I've made some progress on reorganizing the existing ept_entry member functions into helper functions, and have come up with two ways to organize those helpers. Does anyone have a preference on the following two approaches? I personally like **Option 2** better.

### Option 1

Make the ept_entry helpers match the current structure exactly, but the functions belong to a namespace instead of a class. Here's the whole implementation:
* [page_table_entry.h](https://github.com/JaredWright/extended_apis/blob/ept/include/hve/arch/intel_x64/ept/page_table_entry.h)
* [page_table_entry.cpp](https://github.com/JaredWright/extended_apis/blob/ept/src/hve/arch/intel_x64/ept/page_table_entry.cpp)

... and the usage for option 1 would look like this:
```
using namespace eapis::intel_x64::ept::epte;
epte_t entry;
bool result;

set_read_access(entry, 0);    // Disable the read access bit of a page table entry
set_read_access(entry, 1);     // Enable the read access bit of a page table entry
result = read_access(entry); // Check if the read access bit is enabled
```

### Option 2

Make the ept_entry helpers look and feel like the intrinsics. Here's the whole implementation:
* [page_table_entry_2.h](https://github.com/JaredWright/extended_apis/blob/ept/include/hve/arch/intel_x64/ept/page_table_entry_2.h)

... and the usage for option 2 would look like this:
```
using namespace eapis::intel_x64::ept::epte;
epte_t entry;
bool result;

read_access::disable(entry);    // Disable the read access bit of a page table entry
read_access::enable(entry);    // Enable the read access bit of a page table entry
result = read_access::is_enabled(entry); // Check if the read access bit is enabled
result = read_access::is_disabled(entry); // Check if the read access bit is disabled
```

**Comment by connojd** [comment]
I'm a definitely a fan of the intrinsics approach. Also like the names used.

In practice I dont think that the overhead for a walk will be all that bad when you take caching into consideration

:+1:

**Comment by rianquinn** [comment]
I like option #2 as well. Couple of comments:
- Unmap should take a "gpa". Giving it an entry would actually make unmapping pretty hard as all you would have is a "leaf" which would require an entire tree search, while an gpa can be used to unmap in O(1). 
- eptp should return the physical address + the configuration bits. I know it's weird since the last "p" is "pointer", but Intel actually labels eptp in the VMCS as the pointer + configuration bits. 
- attribute_type should default to Read Write, Write Back
- Same comment about unmap

Other than that, this looks great. Good job.

**Comment by JaredWright** [comment]
@rianquinn @connojd:

I'm pretty far into the implementation of this RFC at this point, and wanted to send out another quick status update in case anyone wants some visibility before I'm completely finished. I don't necessarily need any review at this point, just wanted to provided some visibility. Here's the TL;DR of where I'm at:

* The [memory_map.cpp](https://github.com/JaredWright/extended_apis/blob/ept/src/hve/arch/intel_x64/ept/memory_map.cpp) class is pretty far along. It has working functions for adding new pages to the extended page tables, but still needs the unmapping functions and the to_mdl function (which should be easier relative to what's already been completed).
* The memory_map.cpp [unit tests](https://github.com/JaredWright/extended_apis/blob/ept/tests/hve/arch/intel_x64/ept/test_memory_map.cpp) were by *far* the hardest part to get working, but they do seem to be working now! The tricky part was setting up the unit test [support code](https://github.com/JaredWright/extended_apis/blob/ept/tests/hve/arch/intel_x64/ept/ept_test_support.h) just right
* The [helper functions](https://github.com/JaredWright/extended_apis/blob/ept/src/hve/arch/intel_x64/ept/ept_helpers.cpp) on top of the memory_map class have been started, and the [header](https://github.com/JaredWright/extended_apis/blob/ept/include/hve/arch/intel_x64/ept/ept_helpers.h) for those functions shows where I'm planning to go with the rest of the helper functions that aren't there yet. 
* The intinsics-like functions for manipulating [ept entries](https://github.com/JaredWright/extended_apis/blob/ept/include/hve/arch/intel_x64/ept/page_table_entry.h) and their [unit tests](https://github.com/JaredWright/extended_apis/blob/ept/tests/hve/arch/intel_x64/ept/test_page_table_entry.cpp) are pretty much complete at this point

If you want to clone and view the whole branch I'm working from:

```
git clone https://github.com/jaredwright/extended_apis -b ept
```

**Comment by connojd** [comment]
Lookin good! There is a corner case that the ept entry intrinsics doesn't cover. From the note after Table 28-5:

> An entry is present if any bits 2:0 *or bit 10* is 1 if "mode-based execute control for EPT" VM-execution control is 1

We don't enable that control now, but we should probably at least put a debug or alert message if it is enabled. 

Thoughts?

**Comment by JaredWright** [comment]
Great catch, I missed that case completely. I might just add bit 10 to the ```epte::is_present``` intrinsic and have it report that entry as present if that bit is ever set. Weather or not that bit in the entry is valid could be reported by some other function, something like a ```epte::validate``` intrinsic.

**Comment by rianquinn** [comment]
Notes:

- [here](https://github.com/JaredWright/extended_apis/blob/ept/src/hve/arch/intel_x64/ept/memory_map.cpp#L79): you need to use {}. 
- [here](https://github.com/JaredWright/extended_apis/blob/ept/src/hve/arch/intel_x64/ept/memory_map.cpp#L49): Bit masks should be moved to the intrinsics so that this code reads like english. This was an issue with the old code that needed to be fixed. 
- [here](https://github.com/JaredWright/extended_apis/blob/ept/src/hve/arch/intel_x64/ept/memory_map.cpp#L75): Don't use a generic error. Be specific, and include the function name in the error message. 
- [here](https://github.com/JaredWright/extended_apis/blob/ept/src/hve/arch/intel_x64/ept/memory_map.cpp#L79): You are missing spaces between if and (. Please get in the habit of running make format before submitting code for review
- [here](https://github.com/JaredWright/extended_apis/blob/ept/src/hve/arch/intel_x64/ept/memory_map.cpp#L24): Get rid of these. I don't want to memorize namespaces when reading the code. Also, you should be wrapping this code in the namespace itself so that none of this is needed. 
- [here](https://github.com/JaredWright/extended_apis/blob/ept/src/hve/arch/intel_x64/ept/memory_map.cpp#L33): use g_mm->yourmom
- [here](https://github.com/JaredWright/extended_apis/blob/ept/src/hve/arch/intel_x64/ept/memory_map.cpp#L34): The way that you are using new here is wrong. You don't need the opeartor keyword, you should use the new[] syntax, and you should use the () syntax to remove the need for the memset. Also, at some point we are going to have to discuss how we are going to prevent Clang Tidy from getting mad at the use of new. 
- [here](https://github.com/JaredWright/extended_apis/blob/ept/src/hve/arch/intel_x64/ept/memory_map.cpp#L36): Do we really need to cache the PML4. Seems to me the only thing that is needed is to store the EPTP. 
- [here](https://github.com/JaredWright/extended_apis/blob/ept/src/hve/arch/intel_x64/ept/memory_map.cpp#L61): Most of these are not logic errors. Instead, they are runtime errors
- [here](https://github.com/JaredWright/extended_apis/blob/ept/src/hve/arch/intel_x64/ept/memory_map.cpp#L76): Do we need a mutex here?
- [here](https://github.com/JaredWright/extended_apis/blob/ept/src/hve/arch/intel_x64/ept/memory_map.cpp#L78): Use auto, and I don't think there is a need for a reference since your function is returning that. 
- [here](https://github.com/JaredWright/extended_apis/blob/ept/src/hve/arch/intel_x64/ept/memory_map.cpp#L97): This function should call gpa_to_epte, and just return the physical address. Also, any masking should be done int he intrinsics.
- [here](https://github.com/JaredWright/extended_apis/blob/ept/src/hve/arch/intel_x64/ept/memory_map.cpp#L118): Same thing throughout the code, use {} K&R style 
- [here](https://github.com/JaredWright/extended_apis/blob/ept/src/hve/arch/intel_x64/ept/memory_map.cpp#L155): Same thing with all of these. Use g_mm, auto instead of uintptr_t, fix the new operator use.
- [here](https://github.com/JaredWright/extended_apis/blob/ept/src/hve/arch/intel_x64/ept/memory_map.cpp#L174): What is this?
- [here](https://github.com/JaredWright/extended_apis/blob/ept/src/hve/arch/intel_x64/ept/memory_map.cpp#L193): This kind of stuff should be in the intrinsics under EPT. 

I'll likely have more comments, but I think this is a good first start.

**Comment by JaredWright** [comment]
Merged.
